###### topics and services ######

## input topics
topic_in_cloud           : "xtion/depth_registered/points"
topic_in_cloud_old       : ""
topic_in_laser           : ""

## output topics
topic_out_cloud          : "xtion/depth_registered/points_filtered"

###### general settings ######

## input filtering
#skip_count        :    0 # skip no pointcouds
skip_time         : 0.33  # skip all pointclouds within 0.33 seconds
enabled           : true  # node starts activated

## tf
tf_lookup_time    : 0.05   # waiting up to 50 milliseconds

## buffering
buffer_pointcloud : true # save last pointcloud

## extended output for debugging
#debugging         : false # normal output

###### laser ######

## all nans within laserscan will be replaced by this range value
##   if < 0 then this feature will deactivated
#laser_nan_replacement_value: -1 # meter

###### filter ######

filters: ["!sphere: 5 xtion_rgb_optical_frame     # limit xtion"       ,
          "block: 0.8 0.75 1.20 base_link 0 0 0.6 # main body of rover"]
